/**
 * LocationMap Component
 * ---------------------
 * Renders the interactive Leaflet map displaying geographic context.
 * 
 * Default State:
 * - Centered on India [20.5937, 78.9629]
 * - Zoom level 5
 * - No marker initially
 * 
 * Post-Submission State:
 * - Places a pin marker at the entered [latitude, longitude]
 * - Smoothly animates (`flyTo`) the map viewport to the target coordinates at zoom ~9
 * - Displays an information box/popup with current coordinates
 * - Includes visual legend (High/Medium/Low Potential) matching reference image
 * 
 * Future Google Earth Engine (GEE) Integration Hook:
 * The tile layer URL is driven by a configuration prop. To switch to GEE satellite imagery,
 * pass the dynamic tile URL generated by `backend/services/earth_engine_service.py` into `tileUrl`.
 */

import React, { useEffect, useRef } from 'react';
import { MapContainer, TileLayer, Marker, Popup, useMap } from 'react-leaflet';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';

// Custom red map pin SVG icon matching Reference Image 2
const createCustomPinIcon = () => {
  const pinSvg = `
    <svg width="34" height="42" viewBox="0 0 34 42" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path d="M17 0C7.61 0 0 7.61 0 17C0 29.75 17 42 17 42C17 42 34 29.75 34 17C34 7.61 26.39 0 17 0Z" fill="#E53E3E"/>
      <circle cx="17" cy="17" r="6" fill="#FFFFFF"/>
    </svg>
  `;
  return L.divIcon({
    className: 'custom-map-marker',
    html: pinSvg,
    iconSize: [34, 42],
    iconAnchor: [17, 42],
    popupAnchor: [0, -42],
  });
};

const customPin = createCustomPinIcon();

/**
 * Controller child component that uses Leaflet's `useMap()` hook
 * to programmatically fly to new coordinates whenever they change.
 */
const MapViewController = ({ targetLocation, zoomLevel = 9 }) => {
  const map = useMap();

  useEffect(() => {
    if (targetLocation && targetLocation.latitude != null && targetLocation.longitude != null) {
      // Smooth flyTo animation to newly validated coordinates
      map.flyTo([targetLocation.latitude, targetLocation.longitude], zoomLevel, {
        animate: true,
        duration: 1.5,
      });
    }
  }, [targetLocation, zoomLevel, map]);

  return null;
};

const LocationMap = ({ selectedLocation, geeTileUrl = null }) => {
  // Default coordinates centered on India
  const defaultCenter = [20.5937, 78.9629];
  const defaultZoom = 5;

  const hasLocation =
    selectedLocation &&
    selectedLocation.latitude !== null &&
    selectedLocation.longitude !== null;

  return (
    <section className="card map-card" aria-labelledby="map-heading">
      <div className="card-header">
        <h2 id="map-heading" className="card-title">
          Selected Location on Map
        </h2>
      </div>

      <div className="map-container-wrapper">
        <MapContainer
          center={defaultCenter}
          zoom={defaultZoom}
          scrollWheelZoom={true}
          className="leaflet-map-canvas"
        >
          {/* Base OpenStreetMap Tile Layer
              WHERE GOOGLE EARTH ENGINE TILES WILL BE SWAPPED OR OVERLAID:
              If `geeTileUrl` is provided, replace or overlay this TileLayer with the GEE raster tile stream.
          */}
          <TileLayer
            attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
            url={geeTileUrl || 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'}
            maxZoom={19}
          />

          {/* Programmatic camera controller */}
          <MapViewController targetLocation={selectedLocation} zoomLevel={9} />

          {/* Location Marker (rendered only when coordinates are submitted) */}
          {hasLocation && (
            <Marker
              position={[selectedLocation.latitude, selectedLocation.longitude]}
              icon={customPin}
            >
              <Popup>
                <div className="map-popup-content">
                  <strong>Selected Target</strong>
                  <p>Lat: {selectedLocation.latitude.toFixed(4)}</p>
                  <p>Lon: {selectedLocation.longitude.toFixed(4)}</p>
                </div>
              </Popup>
            </Marker>
          )}
        </MapContainer>

        {/* Selected Coordinates Overlay Badge */}
        {hasLocation && (
          <div className="map-coords-badge" role="status">
            <span className="badge-label">Active Coordinates:</span>
            <span className="badge-value">
              {selectedLocation.latitude.toFixed(4)}°, {selectedLocation.longitude.toFixed(4)}°
            </span>
          </div>
        )}

        {/* Map Legend Overlay matching Image 2 */}
        <div className="map-legend-overlay">
          <div className="legend-item">
            <span className="legend-dot dot-high"></span>
            <span className="legend-text">High Potential</span>
          </div>
          <div className="legend-item">
            <span className="legend-dot dot-medium"></span>
            <span className="legend-text">Medium Potential</span>
          </div>
          <div className="legend-item">
            <span className="legend-dot dot-low"></span>
            <span className="legend-text">Low Potential</span>
          </div>
        </div>
      </div>
    </section>
  );
};

export default LocationMap;
